### ISSUE TITLE
Conflitto tra il nome della funzione get_item(list l, int pos) e get_item_pos(list l, int i)

### ISSUE THREAD

**Issue by armandoegger1** [Mantra-Coding/adt-linkedlist#1]
Il secondo parametro della funzione get_item() è chiamato pos creando una correlazione "ipotetica" con la funzione **get_item_POS().** Per una corretta leggibilità e usabilità di quest'ultime, sarebbe meglio rinominarla get_item_INDEX() in modo da trovarci anche con il secondo parametro di tale funzione

**Comment by ScorzielloGiovanni** [comment]
Grazie per la tua attenzione! Pensiamo però che questa correlazione sia impossibile da percepire. Prendendo come esempio la classe **ArrayAdapter** (https://developer.android.com/reference/android/widget/ArrayAdapter) delle librerie Android, al suo interno ci sono due funzioni, **getItem(int position)** (https://developer.android.com/reference/android/widget/ArrayAdapter#getItem(int))  e **getPosition(T item)** (https://developer.android.com/reference/android/widget/ArrayAdapter#getPosition(T)) in cui abbiamo lo stesso tipo di situazione, ma le due funzioni non sono correlate. In più abbiamo inserito anche una buona documentazione proprio per evitare questo tipo di dubbi

**Comment by ScorzielloGiovanni** [comment]
Grazie per la tua attenzione! Pensiamo però che questa correlazione sia impossibile da percepire. Prendendo come esempio la classe
 **ArrayAdapter** (https://developer.android.com/reference/android/widget/ArrayAdapter) 
delle librerie Android, al suo interno ci sono due funzioni: 
> **getItem(int position)** 
   (https://developer.android.com/reference/android/widget/ArrayAdapter#getItem(int))
> **getPosition(T item)** 
   (https://developer.android.com/reference/android/widget/ArrayAdapter#getPosition(T)) 
in cui abbiamo lo stesso tipo di situazione, ma le due funzioni non sono correlate. In più abbiamo inserito anche una buona documentazione proprio per evitare questo tipo di dubbi

**Comment by ScorzielloGiovanni** [comment]
Grazie per la tua attenzione! Pensiamo però che questa correlazione sia impossibile da percepire. Prendendo come esempio la classe
ArrayAdapter (https://developer.android.com/reference/android/widget/ArrayAdapter)
delle librerie Android, al suo interno ci sono due funzioni:

- getItem(int position)
  (https://developer.android.com/reference/android/widget/ArrayAdapter#getItem(int))

- getPosition(T item)
  (https://developer.android.com/reference/android/widget/ArrayAdapter#getPosition(T))

in cui abbiamo lo stesso tipo di situazione, ma le due funzioni non sono correlate. In più abbiamo inserito anche una buona documentazione proprio per evitare questo tipo di dubbi
