### ISSUE TITLE
Clonazione degli elementi in clonelist e reverselist non clona puntatori

### ISSUE THREAD

**Issue by xrenegade100** [Mantra-Coding/adt-linkedlist#4]
Le funzioni _clone_list_ e  _reverse_list_, secondo una mia personale concezione (😛) rispetto al trattamento dei dati di input, dovrebbero creare delle copie delle liste che vengono passate in input come parametri, in particolare per _clone_list_, il cui nome significa proprio questo. Ciò avviene effettivamente per i nodi che la compongono, ma non per gli item (valori) che sono all'interno di essi, se sono di tipo puntatore. Il problema è da ricercare nelle righe di codice successive, tratte da _clone_list_
--
https://github.com/Mantra-Coding/adt-linkedlist/blob/f9b7754ba1c38e859316d8423eb6e45779a4d7ce/list.c#L222-L228

In particolare `p_n->val = p->val; ` funziona correttamente solo se `val` **non è un puntatore, altrimenti ciò che avviene è semplicemente l'assegnamento dell'indirizzo di `p->val` in `p_n->val`, che non equivale a clonare l'item, ma semplicemente ad assegnare al valore del nuovo nodo, l'indirizzo della stessa struttura _"data in input"_**, per cui l'effetto non sarà di clonazione della lista, ma di clonazione dei nodi, che condivideranno, fisicamente, gli stessi oggetti in memoria, e di conseguenza, ogni operazione di modifica dei valori di una delle due liste (originale e clonata) ,tramite dereferenziazione, avrà l'effetto di modificare i valori di entrambe, che secondo la logica della funzione, dovrebbe essere impedita, essendo la lista risultante, indipendente da quella originale.
Esempio:
```C
int main() {
    list l = new_list(); //Immaginiamo riempita con elementi di tipo item (con item puntatore a una struttura)
    list l1 = clone_list(l);
    set_valore(get_item(l1, 1), nuovo_item);
    /*Immaginando che nuovo_item punti ad una struttura allocata in memoria */
}
```
L'effetto del codice precedente è modificare il nodo in posizione 1, di entrambe le liste `l` e `l1`.
Un analogo ragionamento vale per `reverse_list`, che nello stesso modo inserisce elementi nella lista nuova:
https://github.com/Mantra-Coding/adt-linkedlist/blob/f9b7754ba1c38e859316d8423eb6e45779a4d7ce/list.c#L253-L256

La funzione invocata `insert_ontop` si comporta esattamente nello stesso modo di clone_list
https://github.com/Mantra-Coding/adt-linkedlist/blob/f9b7754ba1c38e859316d8423eb6e45779a4d7ce/list.c#L72
E quindi anche gli item dei nodi inseriti "al rovescio" saranno gli stessi (in memoria) che sono nella lista di input. Il comportamento delle funzioni non è quindi quello che ci si aspetta, almeno secondo una mia personale interpretazione logica del motivo per il quale sono state progettate. Chiuderemo questo issue nel momento in cui troveremo una soluzione definitiva che corregge questo "bug" per qualunque definizione di item. :persevere:

**Comment by ScorzielloGiovanni** [comment]
La creazione di una nuova funzione **clone_item(item i)** credo sia la soluzione migliore a questo problema.
La funzione dovrà occuparsi principalmente di due cose:

- allocare lo spazio in memoria per copiare l'item
- inserire i valori dell'item nella sua copia

esempio per una struttura del tipo:

item.h:
```c
typedef struct punto *item;'
```


item.c:
```c
struct punto{
    int ascissa;
    int ordinata;
}
```

In questo caso la funzione sarà:

```c
item clone_item(item i){
	
    item clone = malloc(sizeof(item));
    clone->ascissa = i->ascissa;
    clone->ordinata = i->ordinata;

    return clone;
}
```

Questo mi permette di lasciare immutata l'impelmentazione di **list** indifferentemente da come è strutturato l'item

**Comment by xrenegade100** [comment]
Con https://github.com/Mantra-Coding/adt-linkedlist/commit/884135863ab1d697c1bdbc985b33e9018742937a viene aggiunta `clone_item` in `list.c` nei punti dove c'erano gli assegnamenti sbagliati e in `item.c` come esempio per l'implementazione di item come int.
Quindi chiudo questo issue e nel caso trovassi altre soluzioni aggiunto un commento 😁
